/// Flutter icons Xafeicons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Xafeicons
///      fonts:
///       - asset: fonts/Xafeicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class XafeIcons {
  XafeIcons._();

  static const _kFontFam = 'Xafeicons';
  static const String _kFontPkg = null;

  static const IconData budget = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
